### ISSUE TITLE
media select field type (enhancement request)

### ISSUE THREAD

**Issue by mosheeshel** [mboynes/super-cpt#7] opened 2013-03-20 13:46 UTC
a field that includes a button that opens the media gallery, and when you select a file inserts the url into a text field.

like:
http://www.farinspace.com/wordpress-media-uploader-integration/
https://github.com/farinspace/wpalchemy/blob/dev/wp-content/wpalchemy/MediaAccess.php

In general that project (wpalchemy) has some nice ideas, but your execution, I think is much more elegant (for me as a developer at least)

**Comment by scottlee** [comment] 2013-06-05 20:09
+1

**Comment by mboynes** [comment] 2013-06-15 07:47
Duplicate of #4

**Closed as completed by mboynes** 2013-06-15 07:47 UTC
Labels: duplicate
